import { useMeta } from '../useMeta'

const layers = [
  { index: '01', name: 'Readable record', tagline: 'A person can find the work', desc: 'A portable export begins with a short summary and a plain-text projection of the document. The text is not merely a JSON string hidden inside a private editor state.', contains: ['Title, purpose and export information', 'Plain-text document projection', 'A verifier link or capability declaration'], state: 'Current Inkwave export' },
  { index: '02', name: 'Structured document', tagline: 'The editable source of truth', desc: 'The document tree preserves headings, paragraphs, lists, tables, mathematics, inline formatting, document type and view configuration. It is the representation an editor changes.', contains: ['Versioned content tree', 'Document metadata and email headers where applicable', 'Writer-selected toolbar and reading settings'], state: 'Current Inkwave export' },
  { index: '03', name: 'Sources and citations', tagline: 'Evidence with stable identities', desc: 'Citations use standard bibliographic records and can point to pages, passages and highlights. A portable Studio may include the document library, the cited subset and selected source bytes.', contains: ['CSL/BibTeX-compatible metadata', 'Citation keys, locators and highlights', 'Optional PDFs and other frozen payloads'], state: 'Current, expanding into shared library' },
  { index: '04', name: 'Modules and attachments', tagline: 'Context without duplicate files', desc: 'A central Studio can associate email, source-reader, media and readalong modules. An association identifies an item and how this Studio uses it; it does not silently create a second master copy.', contains: ['Email and document module identity', 'Pictures, movies and isolated audio', 'Stable links back to source items'], state: 'Current modules; shared-library contract in progress' },
  { index: '05', name: 'Voice editions', tagline: 'Audio is not the source text', desc: 'A readalong, character-cast rendering or user recording is a voice edition attached to a stable source revision. Its model, cast, chapter coverage, text mapping and timing can travel without rewriting the book or email it reads.', contains: ['Source ID and source revision', 'Voice/cast, render and timing metadata', 'Chapter coverage and downloadable audio parts'], state: 'Current local implementation; library placement in progress' },
  { index: '06', name: 'Snapshots and provenance', tagline: 'Technical evidence, clearly bounded', desc: 'A grow-only snapshot archive records document states. Signed receipt chains and optional OpenTimestamps proofs bind hashes, not a writer’s text, identity or private keystroke history.', contains: ['Content and bundle hashes', 'Signed receipt-chain material', 'Optional independent timestamp proofs'], state: 'Current Inkwave foundation' },
  { index: '07', name: 'User-controlled library and sync', tagline: 'The master copy belongs to the writer', desc: 'The developing library model separates masters from a Studio’s frozen subset. References and ordinary documents are mutually exclusive classifications; voice editions live separately from their books and emails.', contains: ['Local folder, OneDrive and Google Drive adapters', 'books / bookVoices and emails / emailVoices', 'Immutable webpage snapshots beside their live URL'], state: 'Specified migration path' },
  { index: '08', name: 'Verified Capture', tagline: 'A future desktop-only evidence tier', desc: 'The proposed Tauri desktop layer will bind eligible native input to signed capture intervals. It is designed to raise the cost of ordinary browser automation, never to establish that every sentence was conceived without help.', contains: ['Device and application evidence', 'Verified, inherited, imported and uncertified passage labels', 'Replayable operation chain and explicit interruptions'], state: 'Planned, not yet a public product claim' },
]

function Capability({ state }) {
  const planned = state.startsWith('Planned') || state.includes('in progress') || state.includes('Specified')
  return <span className="arch-badge" data-req={planned ? '0' : '1'}>{state}</span>
}

export default function Architecture() {
  useMeta({ title: 'Architecture', description: 'The current .studio document contract: readable text, structured writing, source evidence, modules, voice editions, provenance and future desktop capture.', path: '/architecture' })
  const shape = '{\n  "v": 1,\n  "summary": { "title": "…", "verifyAt": "…" },\n  "text": "A readable plain-text copy of the work…",\n  "document": { "contentJson": { "type": "doc", "content": [] } },\n  "snapshots": [],\n  "receipts": [],\n  "bibliography": []\n}'
  return (
    <main>
      <div className="container"><div className="page-hero"><p className="page-hero__kicker">The document contract</p><h1 className="page-hero__title">What a <code className="tag">.studio</code> record holds</h1><p className="page-hero__lead">A Studio Document is deliberately layered. Some capabilities already travel in Inkwave exports; others define the next compatible extension rather than a promise a file has already fulfilled.</p></div></div>
      <section><div className="container container--narrow"><p className="section-label">The shape</p><h2>Structured data with readable writing</h2><hr className="divider" /><p>The current format is a versioned JSON container. Its first fields provide a compact human summary and a clean text projection; the <code className="tag">document</code> field holds the editable rich-text tree. This corrects the earlier description of a Markdown header and divider: readable text remains a core goal, but current Inkwave exports carry it as named data rather than an unstructured preamble.</p><pre>{shape}</pre></div></section>
      <section><div className="container"><p className="section-label">Layer reference</p><h2>Capabilities, with their status</h2><p style={{ marginTop: '0.75rem', marginBottom: '1.5rem' }}>The status is part of the specification. “Current” describes shipped or exportable foundations in Inkwave; “in progress” and “planned” describe the intended interoperable contract without pretending it is already universally available.</p><div className="arch-rows">{layers.map(layer => <article className="arch-row" key={layer.index}><div className="arch-card"><div className="arch-card__head"><span className="arch-index">{layer.index}</span><div><h3>{layer.name}</h3><p className="arch-tagline">{layer.tagline}</p></div><Capability state={layer.state} /></div><p className="arch-desc">{layer.desc}</p><ul className="checklist">{layer.contains.map(item => <li key={item}>{item}</li>)}</ul></div></article>)}</div></div></section>
      <section><div className="container container--narrow"><p className="section-label">Compatibility rule</p><h2>Preserve what you do not understand</h2><hr className="divider" /><p>A Studio reader may not implement every optional capability. It should still retain unknown, namespaced or forward-versioned fields on save whenever safe to do so. A missing viewer is not evidence that an attachment or provenance record was absent; the interface must say which is the case.</p><p>Likewise, changing a library item, dropping generated audio or failing to fetch a cloud provider must never quietly rewrite the source evidence preserved by a Studio Document.</p></div></section>
    </main>
  )
}
