import { useState } from 'react'
import { useMeta } from '../useMeta'

const fragments = [
  { id: 'summary', label: 'Readable summary and text', code: '"summary": {\n  "what": "Inkwave provenance record",\n  "title": "On Artificial Languages",\n  "verifyAt": "https://iwzero.me/verify"\n},\n"text": "On Artificial Languages\\n\\nThe dream of a perfect language…"', body: 'These fields let a person quickly identify the record and find a clean textual copy of the work. They are a projection of the document, not a second editable source of truth.' },
  { id: 'document', label: 'Editable document', code: '"document": {\n  "id": "b1fa2bad-…",\n  "title": "On Artificial Languages",\n  "contentJson": {\n    "type": "doc",\n    "content": [{ "type": "paragraph", "content": [] }]\n  },\n  "library": [{ "id": "leibniz1666", "type": "book" }]\n}', body: 'The rich-text tree is the editor’s source of truth. The associated document library can include sources that are cited already as well as sources gathered for the work but not yet quoted.' },
  { id: 'sources', label: 'Citations and source bytes', code: '"bibliography": [{\n  "id": "leibniz1666",\n  "title": "Dissertatio de Arte Combinatoria",\n  "type": "book"\n}],\n"pdfs": {\n  "leibniz1666": { "name": "leibniz-1666.pdf", "data": "…" }\n}', body: 'Bibliographic records are portable data. A deliberate download may include selected source bytes so a recipient can inspect the cited material even without the sender’s library.' },
  { id: 'voice', label: 'Readalong association', code: '"document": {\n  "readalongs": [{\n    "sourceId": "leibniz1666",\n    "editionId": "voice-edition-…",\n    "voice": "Narrator A",\n    "coverage": ["chapter-1", "chapter-2"]\n  }]\n}', body: 'Voice editions identify the source and revision they render. A shared-library implementation stores large audio separately from the source, while portable export may choose to include selected narration bytes.' },
  { id: 'proof', label: 'Snapshots and proof', code: '"snapshots": [{\n  "id": "s1",\n  "contentHash": "9f2c7b1e…",\n  "bundleHash": "d4e9…",\n  "ots": { "status": "confirmed" }\n}],\n"receipts": [{ "period": 1, "signature": "ed25519:…" }]', body: 'A snapshot binds a known document state. Receipts and timestamp proofs can support independent verification, but they are never a magic detector of human thought or AI use.' },
]

export default function Examples() {
  const [active, setActive] = useState(fragments[0])
  useMeta({ title: 'Worked examples', description: 'An annotated current-style .studio record: readable text, editable document, sources, voice associations and bounded provenance.', path: '/examples' })
  return (
    <main>
      <div className="container"><div className="page-hero"><p className="page-hero__kicker">Worked example</p><h1 className="page-hero__title">One record, examined</h1><p className="page-hero__lead">This illustrative <code className="tag">.studio</code> record shows the current vocabulary: readable text, structured writing, a source library, optional voice association, and provenance evidence. It omits large byte payloads for readability.</p></div></div>
      <section><div className="container"><div className="studio-explorer"><div className="studio-explorer__file"><div className="file-example__header"><span className="file-example__dot" /><span className="file-example__dot" /><span className="file-example__dot" /><span style={{ marginLeft: '0.25rem' }}>on-artificial-languages.studio</span></div><div className="studio-explorer__scroll"><pre className="studio-code">{'{\n  "v": 1,\n\n  ' + active.code + '\n\n  // Other compatible fields are retained here.\n}'}</pre></div></div><aside className="studio-explorer__panel"><p className="section-label">Inspect a part</p><div className="studio-explorer__links">{fragments.map(fragment => <button type="button" key={fragment.id} className={'studio-explorer__link' + (active.id === fragment.id ? ' is-active' : '')} onClick={() => setActive(fragment)}>{fragment.label}</button>)}</div><div className="studio-explorer__commentary"><p className="card__label">{active.label}</p><p className="card__body">{active.body}</p></div></aside></div></div></section>
      <section><div className="container container--narrow"><p className="section-label">What the example leaves out</p><h2>The file does not need to contain every master file</h2><hr className="divider" /><p>A writer’s books, PDFs, webpages, emails and voice renderings may be stored in a user-controlled library. A Studio carries the frozen bibliographic records, attachment bytes or narration that make that particular work portable. This avoids turning every essay into an accidental clone of a whole mailbox or audiobook collection.</p></div></section>
    </main>
  )
}
