import { useMeta } from '../useMeta'

const faqs = [
  { q: 'Why not just use .docx or PDF?', a: 'A .docx focuses on editable presentation and a PDF focuses on fixed presentation. A Studio Document can keep a readable text projection, the editable structure, source information, working context and optional verification evidence together. It can still export a normal PDF when a normal PDF is the right thing to send.' },
  { q: 'Is a .studio file readable without Inkwave?', a: 'Yes. It is versioned JSON with a short summary and plain-text representation near the beginning. A person can inspect the writing with ordinary tools; a compatible reader can reconstruct the rich document and any capabilities it supports.' },
  { q: 'Does it copy all my books, email and audio into every document?', a: 'No. The developing library model treats those as master items in your chosen storage. A Studio keeps a frozen subset only when it cites, attaches, quotes or otherwise uses an item. Voice audio is stored separately from its book or email source so it can be removed without harming the original.' },
  { q: 'What does “two copies and no more” mean?', a: 'For each Studio use, there are two durable roles: the master item in your own library and the frozen attachment inside the Studio that uses it. If the same book is used in several Studios, each has its own deliberate frozen attachment; adding it twice to one Studio does not duplicate it. Local thumbnails, indexes, waveforms and downloaded bytes are only evictable caches, never a secret third source of truth.' },
  { q: 'Will a large book or recording slow down my document?', a: 'It should not. Inkwave opens the small document core first: readable text, editable structure and an attachment manifest. Library metadata restores after the first frame, while PDFs, EPUBs, media and voice bytes load only when you open the corresponding reader or player. The design target is a usable cold open no slower than the equivalent Markdown writing.' },
  { q: 'Which source types can it represent?', a: 'The current and specified vocabulary covers PDFs, EPUBs, Markdown and text files, immutable webpage snapshots, email, pictures, movies, isolated audio and readalong editions. Citation records use standard bibliographic metadata and can be moved between a reference collection and ordinary documents without changing their stable identity.' },
  { q: 'Does it record my keystrokes?', a: 'Ordinary Inkwave provenance is built from content hashes, snapshots and signed receipts, not a surveillance log of every keystroke. A future desktop-only Verified Capture mode is explicitly separate and will label the precise evidence it has; it will not claim to prove that a person conceived every sentence alone.' },
  { q: 'How do hashes work, and what do they prove?', a: 'A cryptographic hash is a short fingerprint calculated from the exact content of a document state. The same content produces the same hash; even a tiny edit produces a different one. Inkwave can hash snapshots, link signed receipts to earlier hashes and optionally timestamp a hash. A verifier can then detect later alteration and, where a valid signature or timestamp exists, show that the exact content was signed or existed by a certain time. A hash alone does not identify the writer, reveal how the text was produced, detect AI assistance or prove that the text was entered through Inkwave.' },
  { q: 'Can Inkwave show that a Studio was written without AI?', a: 'Inkwave is being expanded into a desktop application for macOS and Windows. Its planned optional Verified Capture mode will distinguish eligible native editing inside the Inkwave surface from imported or uncertified text, restrict ordinary bulk insertion and browser automation, and sign bounded capture intervals. That should give readers much higher confidence than a normal web document that the certified portions were written in Inkwave without AI insertion. It still cannot guarantee that no AI was used: manual retyping, custom input hardware or a compromised operating system remain outside its proof, and it cannot establish who conceived an idea.' },
  { q: 'Can I build on the format?', a: 'Yes. The standard is published under CC BY 4.0. Implementations should use the name carefully: compatibility means preserving the document contract and being clear about which layers they support.' },
]

export default function FAQ() {
  useMeta({ title: 'FAQ', description: 'Common questions about Studio Documents, master libraries, voice editions, provenance and the Writing Studio Standard.', path: '/faq' })
  return <main><div className="container container--prose"><div className="page-hero"><p className="page-hero__kicker">FAQ</p><h1 className="page-hero__title">Frequently asked questions</h1><p className="page-hero__lead">What the standard is for, what it stores, and where its claims stop.</p></div></div><section><div className="container container--prose"><div className="faq-list">{faqs.map(({ q, a }) => <article className="faq-item" key={q}><h2 className="faq-item__q">{q}</h2><p className="faq-item__a">{a}</p></article>)}</div></div></section></main>
}
